# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode9.3

cache:
 - cocoapods

branches:
   only:
   - master
   - develop

env:
   global:
   - WORKSPACE="SFlowLayoutKit.xcworkspace"
   - IOS_FRAMEWORK_SCHEME="SFlowLayoutKit"
   - EXAMPLE_SCHEME="SFlowLayoutKitExample"

   matrix:
   - DESTINATION="OS=11.3,name=iPhone X"        RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO" ENABLECCODECOVERAGE="NO"
   - DESTINATION="OS=10.3.1,name=iPhone 7 Plus" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"  ENABLECCODECOVERAGE="NO"
   - DESTINATION="OS=9.3,name=iPhone 6"         RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"  ENABLECCODECOVERAGE="NO"
   - DESTINATION="OS=9.3,name=iPhone 6"         RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"  ENABLECCODECOVERAGE="NO"

script:
- carthage update
- set -o pipefail

- if [ $RUN_TESTS == "YES" ]; then
    xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_FRAMEWORK_SCHEME" -destination "$DESTINATION" ENABLE_TESTABILITY=YES test | xcpretty;
  else
    xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_FRAMEWORK_SCHEME" -destination "$DESTINATION" | xcpretty;
  fi

- if [ $BUILD_EXAMPLE == "YES" ]; then
    xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO build | xcpretty;
  fi

- if [ $ENABLECCODECOVERAGE = "YES"]; then
    xcodebuild -enableCodeCoverage YES -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO test | xcpretty;
  fi

# Run `pod lib lint` if specified
- if [ $POD_LINT == "YES" ]; then
    pod lib lint;
  fi

notifications:
   slack: cyrex-group:ByK4WXNdYYjQ1yYZ2tjDOKyr

after_success:
- if [ $ENABLECCODECOVERAGE = "YES" ]; then
    bash <(curl -s https://codecov.io/bash);
  fi
